### PR TITLE
Update run_validate_morph.sh

### PR DESCRIPTION
**Pull request by dfischer049**
Correct the output

### CODE REVIEW

**Comment by mlngan** [comment]
@dfischer049 What is the issue with the output in the existing script?

**Comment by dfischer049** [comment]
It is just a minor output issue. 
You renamed the library by adding the .vXXX part. But this was not represented in the output: "A submission package has been generated..."

**Comment by dfischer049** [comment]
I just propose to set the name for the output archive once and then use it for the actual compression as well as the user notification/cli output

**Comment by mlngan** [comment]
Ok thanks.  I've merged your changes into the master branch.

**Pull request merged**
